FROM nicholasdille/javaruntime:8u111-core
MAINTAINER nicholas.dille@mailbox.org

ADD Git-64-bit.exe /
ADD install.ps1 /
RUN [ "powershell", "-command", "c:\\install.ps1" ]

ADD entry.ps1 /
ENTRYPOINT c:\entry.ps1
CMD [ "c:\\git\\cmd\\git.exe", "--version" ]