FROM microsoft/windowsservercore:10.0.14393.576
MAINTAINER nicholas.dille@mailbox.org

ADD Git-64-bit.exe /
ADD install.ps1 /
RUN [ "powershell", "-command", "c:\\install.ps1" ]

CMD [ "c:\\git\\cmd\\git.exe", "--version" ]